[server]
runOnSave = true
headless = true
maxUploadSize = 2000

[browser]
gatherUsageStats = false

[theme]
base="dark"
primaryColor="#51b265"
backgroundColor="#0a281e"
secondaryBackgroundColor="#22502d"
